# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protomcp < Formula
  desc "Language-agnostic MCP runtime"
  homepage "https://github.com/msilverblatt/protomcp"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.2.0/pmcp_darwin_amd64.tar.gz"
      sha256 "99cec9147f3d7df4597397888fe30bad5e919ff88298930f2bbd5c68a1196315"

      define_method(:install) do
        bin.install "pmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.2.0/pmcp_darwin_arm64.tar.gz"
      sha256 "c91eb1004041e9c6a0bb054ec07d48eb22b878a5a9049f70d433c02401b75780"

      define_method(:install) do
        bin.install "pmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.2.0/pmcp_linux_amd64.tar.gz"
      sha256 "1d13ee4adccd43b7c4c4886973c2ba7f2e081a8348d8d6fbd3e6872f665314ee"
      define_method(:install) do
        bin.install "pmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.2.0/pmcp_linux_arm64.tar.gz"
      sha256 "f896b92493a497b093c56ca89106c5e2d8d3025636105f14c1771ebd1e385942"
      define_method(:install) do
        bin.install "pmcp"
      end
    end
  end
end
