# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protomcp < Formula
  desc "Language-agnostic MCP runtime"
  homepage "https://github.com/msilverblatt/protomcp"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.1.1/pmcp_darwin_amd64.tar.gz"
      sha256 "3f949474d250d8b0e9b185835d38e0bc9a2ebb1dfd2cd0386a7d8880b0eda03a"

      define_method(:install) do
        bin.install "pmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.1.1/pmcp_darwin_arm64.tar.gz"
      sha256 "7eec6724557b3fc145d62e447ced5410526625f4573bcb5516a91bccddc0cab4"

      define_method(:install) do
        bin.install "pmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.1.1/pmcp_linux_amd64.tar.gz"
      sha256 "0b510eee3f36011749aefad00138f90e1a310403e7c6275ea8bd1d377e9c4cf0"
      define_method(:install) do
        bin.install "pmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/msilverblatt/protomcp/releases/download/v0.1.1/pmcp_linux_arm64.tar.gz"
      sha256 "5d4b2d70ae32ae335f51973706ff43c7fdb044f0fa3ab869e78d56c75c5e0eda"
      define_method(:install) do
        bin.install "pmcp"
      end
    end
  end
end
